experiment:
  name: "fus_dict_learning_exp1"
  seed: 42

data:
  raw_data_path: "data/raw/"
  processed_data_path: "data/processed/"
  batch_size: 32
  normalize: True

model:
  name: Top-k sparse autoencoders
  dictionary_size: 100
  sparsity_level: 0.1
  learning_rate: 0.001
  epochs: 50

training:
  optimizer: "adam"
  loss_function: "mse"
  early_stopping: True

logging:
  log_dir: "results/logs/"
  save_model: True
